/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

/**
 *
 * @author ADMIN
 */
public class Pago extends javax.swing.JPanel {

    /**
     * Creates new form Pago
     */
    public Pago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRealizarPago = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        lblNumerodetarjeta = new javax.swing.JLabel();
        txtNumerodetarjeta = new javax.swing.JTextField();
        lblNombredeltitular = new javax.swing.JLabel();
        txtNombredeltitular = new javax.swing.JTextField();
        lblFechadevencimiento = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        lblDia = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblCVV = new javax.swing.JLabel();
        pwdCVV = new javax.swing.JPasswordField();
        btnPagar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblRealizarPago.setFont(new java.awt.Font("Bookman Old Style", 0, 36)); // NOI18N
        lblRealizarPago.setForeground(new java.awt.Color(255, 153, 0));
        lblRealizarPago.setText("Realizar Pago");

        lblMontoTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMontoTotal.setForeground(new java.awt.Color(255, 153, 0));
        lblMontoTotal.setText("Monto total:");

        lblNumerodetarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumerodetarjeta.setForeground(new java.awt.Color(255, 153, 0));
        lblNumerodetarjeta.setText("Numero de tarjeta");

        txtNumerodetarjeta.setBackground(new java.awt.Color(102, 102, 102));
        txtNumerodetarjeta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumerodetarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerodetarjetaActionPerformed(evt);
            }
        });

        lblNombredeltitular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombredeltitular.setForeground(new java.awt.Color(255, 153, 0));
        lblNombredeltitular.setText("Nombre del titular");

        txtNombredeltitular.setBackground(new java.awt.Color(102, 102, 102));
        txtNombredeltitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombredeltitularActionPerformed(evt);
            }
        });

        lblFechadevencimiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechadevencimiento.setForeground(new java.awt.Color(255, 153, 0));
        lblFechadevencimiento.setText("Fecha de vencimineto:");

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMes.setForeground(new java.awt.Color(255, 153, 0));
        lblMes.setText("Mes");

        txtMes.setBackground(new java.awt.Color(102, 102, 102));

        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(255, 153, 0));
        lblDia.setText("Dia");

        txtDia.setBackground(new java.awt.Color(102, 102, 102));

        lblAño.setBackground(new java.awt.Color(255, 255, 255));
        lblAño.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAño.setForeground(new java.awt.Color(255, 153, 0));
        lblAño.setText("Año");

        txtAño.setBackground(new java.awt.Color(102, 102, 102));
        txtAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAñoActionPerformed(evt);
            }
        });

        lblCVV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCVV.setForeground(new java.awt.Color(255, 153, 0));
        lblCVV.setText("cvv");

        pwdCVV.setBackground(new java.awt.Color(102, 102, 102));

        btnPagar.setBackground(new java.awt.Color(255, 153, 0));
        btnPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnPagar.setForeground(new java.awt.Color(255, 255, 255));
        btnPagar.setText("Pagar");

        btnCancelar.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMontoTotal)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblRealizarPago))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNumerodetarjeta)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumerodetarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblNombredeltitular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombredeltitular, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCVV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pwdCVV, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechadevencimiento)
                        .addGap(18, 18, 18)
                        .addComponent(lblDia)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnPagar)
                                .addGap(65, 65, 65)
                                .addComponent(btnCancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMes)
                                .addGap(18, 18, 18)
                                .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRealizarPago)
                .addGap(42, 42, 42)
                .addComponent(lblMontoTotal)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumerodetarjeta)
                    .addComponent(txtNumerodetarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombredeltitular)
                    .addComponent(txtNombredeltitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechadevencimiento)
                    .addComponent(lblDia)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMes)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAño)
                    .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCVV)
                    .addComponent(pwdCVV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPagar)
                    .addComponent(btnCancelar))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumerodetarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerodetarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerodetarjetaActionPerformed

    private void txtNombredeltitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombredeltitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombredeltitularActionPerformed

    private void txtAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAñoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCVV;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFechadevencimiento;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNombredeltitular;
    private javax.swing.JLabel lblNumerodetarjeta;
    private javax.swing.JLabel lblRealizarPago;
    private javax.swing.JPasswordField pwdCVV;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombredeltitular;
    private javax.swing.JTextField txtNumerodetarjeta;
    // End of variables declaration//GEN-END:variables
}
